set(MCP_HOST_INCLUDE_DIRS
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/mac
        ${CMAKE_CURRENT_LIST_DIR}/mt
        ${CMAKE_CURRENT_LIST_DIR}/npi)

set(MCP_HOST_SOURCE_FILES
        ${CMAKE_CURRENT_LIST_DIR}/mcp_host.c
        ${CMAKE_CURRENT_LIST_DIR}/mac/api_mac.h
        ${CMAKE_CURRENT_LIST_DIR}/mac/mac_util.c
        ${CMAKE_CURRENT_LIST_DIR}/mac/mac_util.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt.c
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_ext.c
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_ext.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_mac.c
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_mac.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_pkt.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_rpc.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_sys.c
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_sys.h
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_util.c
        ${CMAKE_CURRENT_LIST_DIR}/mt/mt_util.h
        ${CMAKE_CURRENT_LIST_DIR}/npi/npi_data.h
        ${CMAKE_CURRENT_LIST_DIR}/npi/npi_frame.h
        ${CMAKE_CURRENT_LIST_DIR}/npi/npi_frame_mt.c
        ${CMAKE_CURRENT_LIST_DIR}/osal_port.h)
