set(MCP_HOST_INCLUDE_DIRS
        .
        mac
        mt
        npi)

set(MCP_HOST_SOURCE_FILES
        mcp_host.c
        mac/api_mac.h
        mac/mac_util.c
        mac/mac_util.h
        mt/mt.c
        mt/mt.h
        mt/mt_ext.c
        mt/mt_ext.h
        mt/mt_mac.c
        mt/mt_mac.h
        mt/mt_pkt.h
        mt/mt_rpc.h
        mt/mt_sys.c
        mt/mt_sys.h
        mt/mt_util.c
        mt/mt_util.h
        npi/npi_data.h
        npi/npi_frame.h
        npi/npi_frame_mt.c
        osal_port.h)
